services:
  app:
    build: .
    command: >
      uvicorn app:app
      --host 0.0.0.0
      --port 80
      --proxy-headers
      --forwarded-allow-ips="*"
    env_file: .env
    restart: always

  scanner:
    build: .
    command: python scan.py
    env_file: .env
    restart: always
