services:
  app:
    build: .
    command: >
      uvicorn app:app
      --host 0.0.0.0
      --port 8501
      --proxy-headers
      --forwarded-allow-ips="*"
    env_file: .env
    depends_on:
      - redis
    ports:
      - "8501:8501"     # Publica no host. Use isto se quiser abrir no navegador em localhost:8501
    networks: [web]
    restart: always

  scanner:
    build: .
    command: python scan.py
    env_file: .env
    depends_on:
      - redis
    networks: [web]
    restart: always

networks:
  web: